services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: telemetry-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672" # amqp
      - "15672:15672" # interface
    environment:
      RABBITMQ_DEFAULT_USER: secretUser
      RABBITMQ_DEFAULT_PASS: secretPassword
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_management load_definitions \"/etc/rabbitmq/definitions.json\""
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq-definitions.json:/etc/rabbitmq/definitions.json:ro
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: telemetry-db
    environment:
      POSTGRES_USER: secretUser
      POSTGRES_PASSWORD: secretPassword
      POSTGRES_DB: edge_ingestion
      POSTGRES_INITDB_ARGS: "--wal-segsize=64"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U secretUser -d edge_ingestion"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  rabbitmq_data:
    driver: local
  pg_data:
    driver: local
